#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

echo "
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 396237-web-01 100.25.21.246:80 check
    server 396237-web-02 54.221.183.98:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
