#!/usr/bin/env bash
# print minutes and hours

i=1
j=1

echo "Hour: 0"

while [ $j -lt 14 ]
do
	if [ $i -eq 60 ]
	then
		i=1
		if [ $j -ne 13 ]
		then
			echo "Hour: $j"
		fi
		(( j++ ))
		continue
	fi
	echo $i
	i=$((i + 1))
done
