#!/usr/bin/env bash
# edit the server file

sudo cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost " | tee hosts.tmp
echo "8.8.8.8 facebook.com " | tee -a hosts.tmp
sudo cp -f ~/hosts.new /etc/hosts
